import React from 'react';
import {newOutputField} from './reusableTools';
export default function ReusableSettings({node,onChange,policy}){
 const c=node.config,patch=p=>onChange({...node,config:{...c,...p}});
 return <>
 {['document_extract','external_lookup'].includes(node.kind)&&<>
 {node.kind==='external_lookup'?<label>Public JSON API URL<input placeholder="https://example.org/records/{value}" value={c.endpoint} onChange={e=>patch({endpoint:e.target.value})}/><small>GET request from your browser. Use {'{value}'} for the encoded lookup input. Requires CORS support. Do not put keys or credentials here.</small></label>:<p>Full document text and Text by page are extracted automatically. Connect Full document text to AI to evaluate the content. Scanned pages need OCR, which is not included.</p>}
 <h3>{node.kind==='document_extract'?'Optional labelled fields':'Fields to extract'}</h3>{node.kind==='document_extract'&&<p>Only add these for lines such as “Participant: Alex”. Leave empty when evaluating the whole document.</p>}{c.fields.map((f,i)=><fieldset key={f.id}><legend>Field {i+1}</legend>{['name','label'].map(key=><label key={key}>{key==='name'?'Output name':node.kind==='document_extract'?'Printed label before colon':'JSON path (e.g. record.name)'}<input value={f[key]} onChange={e=>patch({fields:c.fields.map(x=>x.id===f.id?{...x,[key]:e.target.value}:x)})}/></label>)}<label>Data type<select value={f.type} onChange={e=>patch({fields:c.fields.map(x=>x.id===f.id?{...x,type:e.target.value}:x)})}>{['text','number','date','boolean'].map(t=><option key={t}>{t}</option>)}</select></label><button className="mini danger" onClick={()=>patch({fields:c.fields.filter(x=>x.id!==f.id)})}>Remove field</button></fieldset>)}<button className="btn" onClick={()=>patch({fields:[...c.fields,newOutputField()]})}>Add output field</button></>}
 {node.kind==='compare_values'&&<><label>Data type<select value={c.valueType} onChange={e=>onChange({...node,mappings:{},config:{...c,valueType:e.target.value,operator:'eq'}})}>{['text','number','date','boolean'].map(t=><option key={t}>{t}</option>)}</select></label><label>Comparison<select value={c.operator} onChange={e=>patch({operator:e.target.value})}><option value="eq">Equals</option><option value="ne">Does not equal</option>{['number','date'].includes(c.valueType)&&<><option value="gte">At least / on or after</option><option value="lte">At most / on or before</option></>}</select></label>{c.valueType==='text'&&<label><input type="checkbox" checked={c.ignoreCase} onChange={e=>patch({ignoreCase:e.target.checked})}/>Ignore letter case</label>}</>}
 {node.kind==='date_range'&&<>{['start','end'].map(key=><label key={key}>{key==='start'?'Start date':'End date'}<input type="date" value={c[key]} onChange={e=>patch({[key]:e.target.value})}/></label>)}<p>Both boundary dates are included. Missing dates stay uncertain.</p></>}
 {node.kind==='find_duplicates'&&<><p>Compare the two mapped fields against these test records. An empty registry means no matches in this registry only.</p>{c.records.map((r,i)=><fieldset key={i}>{['key','owner'].map(key=><label key={key}>{key==='key'?'Record identifier':'Owner / person identifier'}<input value={r[key]} onChange={e=>patch({records:c.records.map((x,j)=>i===j?{...x,[key]:e.target.value}:x)})}/></label>)}<button className="mini" onClick={()=>patch({records:c.records.filter((_,j)=>i!==j)})}>Remove record</button></fieldset>)}<button className="btn" onClick={()=>patch({records:[...c.records,{key:'',owner:''}]})}>Add test record</button></>}
 {node.kind==='apply_policy'&&<label>Saved policy version<select value={c.policyVersion} onChange={e=>patch({policyVersion:e.target.value})}><option value="">Choose a saved version</option>{(policy?.versions||[]).map(v=><option key={v.version}>{v.version}</option>)}</select><small>Create and save a version in Scoring policy first. This step can use only input fields and earlier outputs; final-outcome rules need a Result instead.</small></label>}
 </>;
}
