import React,{useState} from 'react';
import {newScoringRule,policySources,saveScoringVersion} from './scoringPolicy';
import {PolicyEditor} from './NodeSettings';

export default function ScoringStudio({policy,onChange,fields,nodes,setNodes}){
 const [message,setMessage]=useState('');const sources=policySources(fields,nodes),draft=policy.draft;
 const edit=patch=>{onChange({...policy,draft:{...draft,...patch}});setMessage('');};
 const rule=(id,patch)=>edit({rules:draft.rules.map(r=>r.id===id?{...r,...patch}:r)});
 const legacy=nodes.filter(n=>n.kind==='score'||['action','plugin'].includes(n.kind)&&n.config.tool==='score');
 return <section className="scoring-studio studio"><div className="policy-intro"><h2>Scoring & outcome</h2><p>Rules run in order at an Apply scoring policy step, or at a Result when enabled below. The first matching rule gives the score. Missing evidence keeps the score pending.</p><label className="check-row"><input type="checkbox" checked={policy.enabled} onChange={e=>onChange({...policy,enabled:e.target.checked})}/>Apply this policy to workflow Results</label></div>
 <div className="policy-layout"><div><div className="policy-card"><h3>Draft rules</h3><div className="two-columns"><label>Version name<input value={draft.version} onChange={e=>edit({version:e.target.value})}/></label><label>Maximum points per submission (optional)<input type="number" min="0" step="any" value={draft.maxPoints} onChange={e=>edit({maxPoints:e.target.value})} placeholder="No cap"/></label></div>
 {!draft.rules.length&&<p>Add a rule, choose the information to check, and set its marks.</p>}
 {draft.rules.map((r,i)=><fieldset className="policy-rule" key={r.id}><legend>Rule {i+1}</legend><label>Rule name<input value={r.name} onChange={e=>rule(r.id,{name:e.target.value})}/></label><label>When<select value={r.match} onChange={e=>rule(r.id,{match:e.target.value})}><option value="all">All conditions match</option><option value="any">Any condition matches</option></select></label>
 {r.conditions.map((c,j)=>{const change=patch=>rule(r.id,{conditions:r.conditions.map((x,k)=>k===j?{...x,...patch}:x)});return <div className="policy-condition" key={j}><label>Information<select value={c.source} onChange={e=>{const source=sources.find(s=>s.value===e.target.value);change({source:e.target.value,type:source?.type||'text',operator:'eq',expected:''});}}><option value="">Choose information</option>{sources.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select>{!sources.some(s=>s.value===c.source&&s.type===c.type)&&<small className="error">Select a compatible source again.</small>}</label><label>Comparison<select value={c.operator} onChange={e=>change({operator:e.target.value})}><option value="eq">Equals</option><option value="ne">Does not equal</option>{['date','number'].includes(c.type)&&<><option value="gte">At least / on or after</option><option value="lte">At most / on or before</option></>}</select></label><label>Value{c.type==='boolean'?<select value={c.expected} onChange={e=>change({expected:e.target.value})}><option value="">Choose</option><option value="true">Yes</option><option value="false">No</option></select>:<input type={['number','date'].includes(c.type)?c.type:'text'} value={c.expected} onChange={e=>change({expected:e.target.value})}/>}</label><button className="mini" aria-label={`Remove condition ${j+1} from ${r.name}`} onClick={()=>rule(r.id,{conditions:r.conditions.filter((_,k)=>k!==j)})}>Remove</button></div>;})}
 <button className="mini" onClick={()=>rule(r.id,{conditions:[...r.conditions,{source:'result|outcome',type:'text',operator:'eq',expected:''}]})}>+ Condition</button><div className="three-columns"><label>Points<input type="number" min="0" step="any" value={r.points} onChange={e=>rule(r.id,{points:e.target.value})}/></label><label>Multiplier<input type="number" min="0" step="any" value={r.multiplier} onChange={e=>rule(r.id,{multiplier:e.target.value})}/></label><label>Scoring outcome<input value={r.outcome} onChange={e=>rule(r.id,{outcome:e.target.value})}/></label></div><div className="button-row"><button className="mini" disabled={!i} onClick={()=>{const rules=[...draft.rules];[rules[i-1],rules[i]]=[rules[i],rules[i-1]];edit({rules});}}>Move up</button><button className="mini danger" onClick={()=>edit({rules:draft.rules.filter(x=>x.id!==r.id)})}>Remove rule</button></div></fieldset>)}
 <button className="btn" onClick={()=>edit({rules:[...draft.rules,newScoringRule()]})}>+ Add rule</button><label>If no rule matches<select value={draft.fallback} onChange={e=>edit({fallback:e.target.value})}><option value="pending">Pending review</option><option value="zero">Award zero points</option></select></label><small>This fallback applies only after every rule is confirmed not to match. Missing evidence stays pending.</small></div>
 {legacy.length>0&&<details className="policy-card"><summary>Existing publication policies ({legacy.length})</summary><p>These policies still run inside their Calculate marks steps, before appraiser review. Your existing rules are preserved.</p>{legacy.map(n=><div key={n.id}><h3>{n.name}</h3><PolicyEditor policy={n.kind==='score'?n.config.policy:n.config.settings.policy} onChange={updated=>setNodes(nodes.map(x=>x.id!==n.id?x:{...x,config:x.kind==='score'?{...x.config,policy:updated}:{...x.config,settings:{...x.config.settings,policy:updated}}}))}/></div>)}</details>}
 </div><aside className="policy-card policy-versions"><h3>Versions used in tests</h3><p>Draft edits autosave. Save a new version to use those rules in a test. Existing versions cannot be overwritten.</p><button className="btn primary" onClick={()=>{try{onChange(saveScoringVersion(policy,fields,nodes));setMessage('Version saved and selected for testing.');}catch(e){setMessage(e.message);}}}>Save policy version</button>{message&&<p role="status">{message}</p>}<label>Selected version<select value={policy.activeVersion} onChange={e=>onChange({...policy,activeVersion:e.target.value})}><option value="">No version selected</option>{policy.versions.map(v=><option key={v.version}>{v.version}</option>)}</select></label><p>{policy.enabled?'Policy is enabled.':'Automatic Result scoring is off. Apply scoring policy steps can still use a saved version.'}</p>{policy.versions.map(v=><details key={v.version}><summary>{v.version} - {v.rules.length} rules</summary><ul>{v.rules.map(r=><li key={r.id}>{r.name}: {r.points} x {r.multiplier}</li>)}</ul><button className="mini" onClick={()=>edit({...structuredClone(v),version:`${v.version}-copy`})}>Copy to draft</button></details>)}<small>Policies score test submissions only. Human reviews and results remain session-only.</small></aside></div></section>;
}
