import {reusableIssues} from './reusableTools';
import PluginPicker from './PluginPicker';
import React,{useMemo,useRef,useState} from 'react';
import {Plus,X,Search,GripVertical,GitBranch,FileText,CheckCircle2,Settings2,Minus,Undo2,Library,Maximize2} from 'lucide-react';
import {tools,blocks,nodeDefinition,sourceChoices,createNode} from './workflowModel';
import {insertStep,moveStep,removeStep,layoutTree,orderedNodes,hasCycle} from './treeModel';
import NodeSettings from './NodeSettings';
import './tree.css';
const branchLabel=(r,kind)=>kind==='condition'&&r==='clear'?'Met':({next:'Continue',clear:'Clear',uncertain:'Needs review',ineligible:'Ineligible',failed:'Not met',approved:'Approved',rejected:'Rejected',clarification:'Clarify'}[r]||r);
const purpose=k=>({submit:'Start · receive a submission',extract:'Read evidence from a PDF',lookup:'Find a publication record',compare:'Compare two sources',author:'Match the first author',period:'Check assessment dates',index:'Check mock index evidence',duplicate:'Find earlier submissions',decision:'Split into three paths',ai:'Run your AI instructions',score:'Apply your scoring policy',review:'Wait for an appraiser'}[k]);
function statusFor(n,nodes,fields){const d=nodeDefinition(n);const kind=['action','plugin'].includes(n.kind)?n.config.tool:n.kind;const config=['action','plugin'].includes(n.kind)?n.config.settings:n.config;if(['action','plugin'].includes(n.kind)&&!n.config.tool)return 'Choose a tool';if(reusableIssues({...n,kind,config}).length)return 'Needs setup';if(n.kind==='condition'&&!n.config.expected)return 'Set comparison';if(n.kind==='result'&&!n.config.outcome.trim())return 'Name outcome';if(n.kind==='human_review'&&!n.config.role.trim())return 'Choose reviewer';if(d.inputs.some(p=>(!p.optional||n.mappings[p.key])&&!sourceChoices(n,p,nodes,fields).some(c=>c.value===n.mappings[p.key])))return 'Needs setup';if(kind==='lookup'&&!n.mappings.doi&&!n.mappings.url)return 'Needs setup';if(kind==='period'&&(!config.start||!config.end))return 'Needs dates';if(n.kind==='submit'&&!fields.length)return 'Add input fields';if(Object.values(n.routes).some(r=>!r||!nodes.some(x=>x.id===r)))return 'Connect next step';return 'Configured';}
export default function TreeBuilder({nodes,fields,onChange,disabled,onExample,toolbarStart,initialSelected='',policy}){
 const [pluginTarget,setPluginTarget]=useState(null);
 const [selected,setSelected]=useState(initialSelected);const [library,setLibrary]=useState(false);const [query,setQuery]=useState('');const [slot,setSlot]=useState(null);const [zoom,setZoom]=useState(1);const [message,setMessage]=useState('');const [dragging,setDragging]=useState(null);const [moving,setMoving]=useState(null);const [undo,setUndo]=useState([]);const viewport=useRef(null);const graph=useMemo(()=>layoutTree(nodes),[nodes]);const node=nodes.find(n=>n.id===selected);
 const commit=next=>{setUndo(prev=>[...prev.slice(-14),nodes]);onChange(next);setMessage('');};
 const place=(item,target)=>{if(disabled)return;if(item.kind==='plugin'){setPluginTarget({target});return;}try{if(item.id){commit(moveStep(nodes,item.id,target.id,target.route));setSelected('');}else{const result=insertStep(nodes,fields,item.kind,target?.id,target?.route);commit(result.nodes);setSelected(result.selected);}setMoving(null);setSlot(null);setLibrary(false);}catch(e){setMessage(e.message);}setDragging(null);};
 const openSlot=target=>{if(moving){place({id:moving},target);return;}setSlot(target);setLibrary(true);setSelected('');};
 const beginDrag=(event,item)=>{event.dataTransfer.setData('application/afpi-step',JSON.stringify(item));event.dataTransfer.effectAllowed=item.id?'move':'copy';setDragging(item);};
 const drop=(e,target)=>{e.preventDefault();try{const item=JSON.parse(e.dataTransfer.getData('application/afpi-step'));if(item.id||blocks.some(t=>t.kind===item.kind))place(item,target);}catch{setMessage('Drag a step from this workflow or its tool library.');}setDragging(null);};
 const slotButton=(id,route,x,y)=><button key={`${id}-${route}`} className={`tree-slot ${dragging||moving?'accepting':''} ${slot?.id===id&&slot?.route===route?'chosen':''}`} style={{left:x-16,top:y}} data-source={id} data-route={route} aria-label={`Add step ${branchLabel(route,nodes.find(n=>n.id===id)?.kind).toLowerCase()} after ${nodes.find(n=>n.id===id)?.name||'submission'}`} disabled={disabled} onClick={()=>openSlot({id,route})} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect=dragging?.id?'move':'copy';}} onDrop={e=>drop(e,{id,route})}><Plus size={17}/></button>;
 const fit=()=>{if(!viewport.current)return;setZoom(Math.min(1,Math.max(.3,(viewport.current.clientWidth-70)/graph.width)));viewport.current.scrollTo({top:0,left:0});};
 const chooseTool=t=>{if(t.kind==='plugin'){setPluginTarget({target:slot});return;}if(slot||!nodes.length)place({kind:t.kind},slot);else{setMoving(null);setDragging(null);setMessage('Choose a + on the tree, or drag this tool onto one.');}};
 return <div className="tree-builder">{pluginTarget&&<PluginPicker onClose={()=>setPluginTarget(null)} onChoose={(plugin,kind)=>{try{const target=pluginTarget.target;if(nodes.length&&!target){setMessage('Choose a + first to place the plugin tool.');setPluginTarget(null);return;}const result=insertStep(nodes,fields,kind,target?.id,target?.route);commit(result.nodes.map(n=>n.id===result.selected?{...n,kind:'plugin',config:{plugin,tool:kind,settings:n.config}}:n));setSelected(result.selected);setPluginTarget(null);setLibrary(false);setSlot(null);}catch(e){setMessage(e.message);setPluginTarget(null);}}}/>}<div className="tree-toolbar">{toolbarStart}<button className={`btn ${library?'primary':''}`} onClick={()=>{setLibrary(!library);setSelected('');}} disabled={disabled}><Library size={16}/>Blocks</button><span>{nodes.length?`${nodes.length} steps`:'Start your workflow'}</span>{nodes.length>0&&!nodes.some(n=>n.kind==='submit')&&<button className="btn" disabled={disabled} onClick={()=>{const root={...createNode('submit'),name:'Submission received'};root.routes.next=orderedNodes(nodes)[0].id;commit([root,...nodes]);}}>Add starting trigger</button>}<div className="tree-toolbar-right"><button aria-label="Undo last edit" disabled={disabled||!undo.length} onClick={()=>{onChange(undo.at(-1));setUndo(undo.slice(0,-1));setSelected('');setMessage('Last edit undone.');}}><Undo2 size={16}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.3,z-.1))}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.3,z+.1))}><Plus size={16}/></button><button aria-label="Fit tree width" onClick={fit}><Maximize2 size={16}/></button></div></div>
 {message&&<div className="tree-message" role="status">{message}<button aria-label="Dismiss canvas message" onClick={()=>setMessage('')}><X size={14}/></button></div>}{moving&&<div className="tree-message">Choose a + to move this step.<button onClick={()=>setMoving(null)}>Cancel move</button></div>}
 <div className="tree-workspace">
 {library&&<aside className="tree-library"><div className="tree-panel-heading"><h3>Building blocks</h3><button aria-label="Close tool library" onClick={()=>{setLibrary(false);setSlot(null);}}><X size={18}/></button></div><p>{slot?'Choose a tool for the selected +.':'Drag a tool onto a + in your workflow.'}</p><label className="tree-search"><Search size={16}/><input aria-label="Search tools" placeholder="Search tools" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="tree-library-items">{blocks.filter(t=>`${t.name} ${t.description}`.toLowerCase().includes(query.toLowerCase())).map(t=><button key={t.kind} draggable={!disabled} onDragStart={e=>beginDrag(e,{kind:t.kind})} onDragEnd={()=>setDragging(null)} onClick={()=>chooseTool(t)} disabled={disabled}><GripVertical size={15}/><span><strong>{t.name}</strong><small>{t.description}</small></span><Plus size={14}/></button>)}</div><p className="tree-library-note">Choose a tool inside Action, then connect its inputs.</p></aside>}
 <div className="tree-viewport" ref={viewport}><div className="tree-scroll-space" style={{width:graph.width*zoom,height:graph.height*zoom,minWidth:'100%'}}><div className="tree-plane" style={{width:graph.width,height:graph.height,transform:`scale(${zoom})`,left:`max(0px, calc((100% - ${graph.width*zoom}px) / 2))`}}>
 {!nodes.length?<><div className="tree-start"><span className="tree-node-icon"><FileText size={20}/></span><div><span className="tree-overline">TRIGGER</span><strong>Submission received</strong><small>Your input form starts this workflow.</small></div></div><div className="tree-start-line"/>{slotButton('', 'next',graph.width/2,222)}<div className="tree-start-help"><strong>What should happen next?</strong><p>Click + to choose a block, or open the library and drag one here.</p><button onClick={onExample} disabled={disabled}>Explore the publication example</button></div></>:<>
 <svg className="tree-connectors" width={graph.width} height={graph.height} aria-hidden="true">{nodes.flatMap(n=>Object.entries(n.routes).map(([route,target],i)=>{const a=graph.points.get(n.id),b=graph.points.get(target);if(!a||!b)return null;const count=Object.keys(n.routes).length;const sx=a.x+(i-(count-1)/2)*80,sy=a.y+112,ey=b.y;const long=b.rank-a.rank>1||ey<=sy;const gutter=graph.width-45-i*20;const path=long?`M ${sx} ${sy} V ${sy+70} H ${gutter} V ${ey-22} H ${b.x} V ${ey}`:`M ${sx} ${sy} V ${sy+80} H ${b.x} V ${ey}`;return <path key={`${n.id}-${route}`} d={path} className={`route-${route}`}/>;}))}</svg>
 {nodes.map(n=>{const p=graph.points.get(n.id);const status=statusFor(n,nodes,fields);const movable=n.kind!=='submit'&&Object.keys(n.routes).length===1;return <React.Fragment key={n.id}><article className={`tree-node ${selected===n.id?'selected':''} ${!graph.reachable.has(n.id)?'unconnected':''}`} style={{left:p.x-140,top:p.y}}><button className="tree-node-body" onClick={()=>{setSelected(n.id);setLibrary(false);setMoving(null);}} disabled={disabled}><span className="tree-node-icon">{['decision','condition'].includes(n.kind)?<GitBranch size={20}/>:n.kind==='submit'?<FileText size={20}/>:<Settings2 size={19}/>}</span><div><span className="tree-overline">{n.kind==='submit'?'TRIGGER':['decision','condition'].includes(n.kind)?'BRANCH':['review','human_review'].includes(n.kind)?'HUMAN REVIEW':n.kind==='result'?'RESULT':n.kind==='plugin'?'PLUGIN':'ACTION'}</span><strong>{n.kind==='submit'&&n.name==='Submit paper'?'Submission received':n.name}</strong><small>{purpose(n.kind)||nodeDefinition(n).description}</small></div></button><div className="tree-node-footer"><span className={status==='Configured'?'ready':'needs'}>{status==='Configured'&&<CheckCircle2 size={11}/>} {!graph.reachable.has(n.id)?'Not connected':status}</span>{movable&&<button className="tree-drag" draggable={!disabled} onDragStart={e=>beginDrag(e,{id:n.id})} onDragEnd={()=>setDragging(null)} onClick={()=>{setMoving(n.id);setSelected('');setMessage('');}} aria-label={`Move ${n.name}`} title="Drag to a +, or click then choose a +"><GripVertical size={15}/></button>}</div></article>{Object.keys(n.routes).map((r,i)=>{const count=Object.keys(n.routes).length;const x=p.x+(i-(count-1)/2)*80;return <React.Fragment key={r}>{count>1&&<span className={`tree-branch-label label-${r}`} style={{left:x-39,top:p.y+125}}>{branchLabel(r,n.kind)}</span>}{!n.routes[r]&&<div className="tree-short-line" style={{left:x,top:p.y+112,height:count>1?66:43}}/>}{slotButton(n.id,r,x,p.y+(count>1?174:151))}</React.Fragment>;})}</React.Fragment>;})}
 </>}
 </div></div></div>
 {node&&<div className="tree-drawer"><div className="tree-panel-heading"><strong>Step settings</strong><button aria-label="Close step settings" onClick={()=>setSelected('')}><X size={18}/></button></div><fieldset disabled={disabled}><NodeSettings policy={policy} node={node} nodes={nodes} fields={fields} onChange={updated=>{const next=nodes.map(n=>n.id===updated.id?updated:n);if(hasCycle(next)){setMessage('That connection would create a loop. Choose a later step.');return;}commit(orderedNodes(next));}} onRemove={()=>{if(node.kind==='submit'&&nodes.length>1){setMessage('Keep the submission trigger as the starting point. Remove its other steps first if you want an empty workflow.');return;}commit(removeStep(nodes,node.id));setSelected('');setMessage('Step removed. Any affected input mappings can be updated in settings.');}}/></fieldset></div>}
 </div><div className="tree-bottom"><span>Drag blocks onto + · Click a step to configure it</span>{graph.cycle&&<span className="error">This saved workflow contains a loop. Update its connections.</span>}</div></div>;
}
