import test from 'node:test';
import assert from 'node:assert/strict';
import {exampleWorkflow,defaultPolicy,createNode,sourceChoices} from './workflowModel.js';
import {runWorkflow,validateWorkflow,calculateScore,finalizeReview,lookupPublication,crossrefRecord,checkPeriod,checkDuplicates,checkIndex,compareEvidence,executeNode,validateSubmission} from './workflowEngine.js';
const doi='10.1371/journal.pmed.1003583';
const fields=[{id:'pdf',label:'Research paper',type:'file',required:true,accept:'.pdf'},{id:'doi',label:'DOI',type:'text'},{id:'url',label:'Publication URL',type:'url'},{id:'faculty',label:'Faculty name',type:'text',required:true}];
const values={pdf:[{name:'paper.pdf',type:'application/pdf'}],doi,url:`https://doi.org/${doi}`,faculty:'Matthew J. Page'};
const metadata={status:'found',doi,title:'The PRISMA 2020 statement',journal:'PLOS Medicine',authors:[{name:'Matthew J. Page'},{name:'Joanne E. McKenzie'}],dates:{published:'2021-03-29'},source:'test fixture'};
const paper={pageCount:1,pages:[{number:1,text:'Matthew J. Page'}],findings:[{name:'Title',value:metadata.title},{name:'DOI',value:[doi]},{name:'Journal / publication',value:metadata.journal},{name:'Authors in order',value:'Matthew J. Page, Joanne E. McKenzie'},{name:'Publication dates',value:['Published: March 29, 2021']}]};
function setup(){const nodes=exampleWorkflow(fields);nodes.find(n=>n.kind==='ai').config.mode='disabled';return {nodes,fields,values:structuredClone(values),extract:async()=>structuredClone(paper),lookup:async()=>structuredClone(metadata)};}
test('publication tools execute inside reusable Actions with original evidence and score',async()=>{
 const cfg=setup();cfg.nodes=cfg.nodes.map(n=>['submit','decision','review'].includes(n.kind)?n:{...n,kind:'action',config:{tool:n.kind,settings:n.config}});
 const run=await runWorkflow(cfg);assert.equal(run.status,'awaiting-review');assert.equal(run.review.score.points,24);
 assert.equal(run.trace.find(s=>s.kind==='extract').output.paper.pageCount,1);
 assert.equal(run.trace.find(s=>s.kind==='score').output.points,24);
});
test('complete clear route produces 24, skips AI, pauses for human, and preserves policy snapshot',async()=>{const cfg=setup();assert.deepEqual(validateWorkflow(cfg.nodes,fields),[]);const r=await runWorkflow(cfg);assert.equal(r.status,'awaiting-review');assert.equal(r.trace.length,11);assert.equal(r.review.score.points,24);assert(!r.trace.some(s=>s.kind==='ai'));cfg.nodes.find(n=>n.kind==='score').config.policy.rules[0].points=99;assert.equal(r.review.score.policy.rules[0].points,24);const f=finalizeReview(r,{action:'approve',reviewer:'Appraiser'});assert.equal(f.approvedScore,24);assert.equal(f.simulated,true);});
test('single index policy produces 12; custom policy rule and multiplier are executed',async()=>{const cfg=setup();cfg.nodes.find(n=>n.kind==='index').config.registry[0].wos='no';const r=await runWorkflow(cfg);assert.equal(r.review.score.points,12);const p=defaultPolicy();p.rules[1].points=20;p.rules[1].multiplier=.5;p.version='custom-v2';assert.equal(calculateScore(r.review.decision,p).points,10);});
test('unknown index follows AI rehearsal route; cannot approve unresolved score',async()=>{const cfg=setup();cfg.nodes.find(n=>n.kind==='index').config.registry=[];cfg.nodes.find(n=>n.kind==='ai').config.mode='simulated';const r=await runWorkflow(cfg);assert.equal(r.review.decision.status,'uncertain');assert.equal(r.review.assistance.status,'simulated');assert.equal(r.review.score,null);assert.throws(()=>finalizeReview(r,{action:'approve',reviewer:'Reviewer'}),/Unresolved/);assert.throws(()=>finalizeReview(r,{action:'override',reviewer:'Reviewer',points:12}),/reason/);const f=finalizeReview(r,{action:'override',reviewer:'Reviewer',points:12,reason:'Reviewed original evidence in this test'});assert.equal(f.originalScore,null);assert.equal(f.approvedScore,12);});
test('outside assessment routes to review as ineligible zero; inclusive boundaries',async()=>{const cfg=setup();cfg.nodes.find(n=>n.kind==='period').config.start='2022-01-01';cfg.nodes.find(n=>n.kind==='period').config.end='2022-12-31';const r=await runWorkflow(cfg);assert.equal(r.review.decision.status,'ineligible');assert.equal(finalizeReview(r,{action:'approve',reviewer:'R'}).approvedScore,0);assert.equal(checkPeriod(metadata,{start:'2021-03-29',end:'2021-03-29',dateRule:'published'}).status,'eligible');assert.equal(checkPeriod(metadata,{start:'2021-01-01',end:'2021-12-31',dateRule:'published-online'}).status,'uncertain');});
test('lookup failures continue as uncertain instead of scoring zero',async()=>{const cfg=setup();cfg.lookup=async()=>({status:'unknown',reason:'Network unavailable',doi});const r=await runWorkflow(cfg);assert.equal(r.status,'awaiting-review');assert.equal(r.review.decision.status,'uncertain');assert.equal(r.review.score,null);assert.equal(r.review.assistance.status,'not-connected');});
test('DOI conflicts prevent external lookup',async()=>{const cfg=setup();cfg.values.url='https://doi.org/10.1000/conflict';let called=false;cfg.lookup=async()=>{called=true;return metadata;};const r=await runWorkflow(cfg);assert.equal(called,false);assert.equal(r.review.decision.status,'uncertain');});
test('duplicate review scoped to same DOI and faculty; another coauthor allowed',async()=>{assert.equal(checkDuplicates(metadata,'Matthew J. Page',[{doi,faculty:'Joanne E. McKenzie'}]).status,'clear');const cfg=setup();cfg.records=[{doi,faculty:'Matthew J Page'}];const r=await runWorkflow(cfg);assert.equal(r.review.decision.facts.duplicate,'candidate');assert.equal(r.review.score,null);});
test('non-primary faculty never silently gets primary points',async()=>{const cfg=setup();cfg.values.faculty='Joanne E. McKenzie';const r=await runWorkflow(cfg);assert.equal(r.review.decision.facts.primary,'no');assert.equal(r.review.decision.status,'uncertain');assert.equal(r.review.score,null);});
test('missing required inputs stop before PDF or network',async()=>{const cfg=setup();delete cfg.values.pdf;let calls=0;cfg.extract=async()=>{calls++;return paper;};const r=await runWorkflow(cfg);assert.equal(r.status,'error');assert.equal(calls,0);assert.match(r.issues[0],/required/);});
test('damaged PDF stops with an actionable extraction error',async()=>{const cfg=setup();cfg.extract=async()=>{throw Error('This file is not a PDF.');};const r=await runWorkflow(cfg);assert.equal(r.status,'error');assert.match(r.issues[0],/not a PDF/);});
test('missing text and conflicting title remain uncertain',()=>{assert.equal(compareEvidence({...paper,findings:[]},metadata).status,'uncertain');assert.equal(compareEvidence(paper,{...metadata,title:'Other paper'}).status,'uncertain');});
test('removed mappings, later sources, cycles, disconnected nodes and bypasses rejected',()=>{for(const mutate of [n=>n.find(x=>x.kind==='extract').mappings.file='field|gone',n=>n.find(x=>x.kind==='extract').routes.next=n[0].id,n=>n.find(x=>x.kind==='submit').routes.next=n.find(x=>x.kind==='decision').id,n=>n.push(createNode('lookup'))]){const cfg=setup();mutate(cfg.nodes);assert(validateWorkflow(cfg.nodes,fields).length);}});
test('source chooser offers only compatible earlier results',()=>{const cfg=setup();const compare=cfg.nodes.find(n=>n.kind==='compare');const options=sourceChoices(compare,{type:'paper'},cfg.nodes,fields);assert.equal(options.length,1);assert.match(options[0].label,/Extract/);assert(!options.some(o=>/Faculty/.test(o.label)));});
test('partial dates and out-of-coverage registry do not imply eligible or not indexed',()=>{const m=crossrefRecord({DOI:doi,published:{'date-parts':[[2021]]}},'fixture');assert.equal(m.dates.published,null);assert.equal(checkIndex(metadata,[{doi,start:'2022-01-01',end:'2022-12-31',scopus:'no',wos:'no'}]).scopus,'unknown');});
test('network adapter classifies 404 and malformed responses',async()=>{assert.equal((await lookupPublication(doi,async()=>({ok:false,status:404}))).status,'unknown');assert.equal((await lookupPublication(doi,async()=>({ok:true,json:async()=>({message:{DOI:'10.1000/wrong'}})}))).status,'unknown');assert.equal((await lookupPublication(doi,async()=>{throw Error('offline');})).status,'unknown');});
test('dynamic validation handles booleans, files, numeric values and removed options',()=>{assert.deepEqual(validateSubmission([{id:'b',label:'Answer',type:'boolean',required:true}],{b:'No'}),[]);assert(validateSubmission([{id:'n',label:'Count',type:'integer'}],{n:1.5}).length);assert(validateSubmission([{id:'f',label:'PDF',type:'file',accept:'.pdf'}],{f:[{name:'x.exe'}]}).length);assert(validateSubmission([{id:'s',label:'Choice',type:'select',options:'One'}],{s:'Gone'}).length);});
test('no matching policy stays pending; invalid point values fail',()=>{const decision={status:'clear',facts:{primary:'yes',period:'eligible',duplicate:'clear',scopus:'no',wos:'no'}};assert.equal(calculateScore(decision,defaultPolicy()).points,null);const p=defaultPolicy();p.rules[0].points=-1;assert.throws(()=>calculateScore(decision,p),/non-negative/);});
test('AI no-connection mode is explicit and cannot change facts',async()=>{const node=createNode('ai');node.config.mode='disabled';const decision={status:'uncertain',reasons:['Identity unclear']};const {assistance}=await executeNode(node,{decision},{});assert.equal(assistance.status,'not-connected');assert.equal(assistance.decision,decision);});
test('OpenRouter node receives uncertain findings and cannot change the verification result',async()=>{const cfg=setup();cfg.nodes.find(n=>n.kind==='index').config.registry=[];cfg.nodes.find(n=>n.kind==='ai').config.mode='openrouter';let calls=0;cfg.ai=async d=>{calls++;assert.equal(d.status,'uncertain');return {status:'advisory',summary:'Check index evidence',points:999};};const r=await runWorkflow(cfg);assert.equal(calls,1);assert.equal(r.review.decision.status,'uncertain');assert.equal(r.review.score,null);assert.throws(()=>finalizeReview(r,{action:'approve',reviewer:'R'}),/Unresolved/);});
test('submitted DOI mismatch is cross-checked against the extracted identifier',async()=>{const cfg=setup();cfg.values.doi='10.1000/different';let calls=0;cfg.lookup=async()=>{calls++;return metadata;};const r=await runWorkflow(cfg);assert.equal(calls,0);assert.equal(r.review.decision.status,'uncertain');});
test('review decisions require identity and reason; cannot finalize twice',async()=>{const r=await runWorkflow(setup());assert.throws(()=>finalizeReview(r,{action:'approve'}),/name/);for(const action of ['reject','clarify','override'])assert.throws(()=>finalizeReview(r,{action,reviewer:'R'}),/reason/);assert.equal(finalizeReview(r,{action:'reject',reviewer:'R',reason:'Not eligible'}).approvedScore,0);assert.equal(finalizeReview(r,{action:'clarify',reviewer:'R',reason:'Provide original'}).approvedScore,null);assert.throws(()=>finalizeReview({...r,status:'reviewed'},{action:'approve',reviewer:'R'}),/no longer/);});

test('publication plugin preserves clear, uncertain and ineligible routing and review',async()=>{
 for(const outcome of ['clear','uncertain','ineligible']){
 const cfg=setup();if(outcome==='uncertain')cfg.nodes.find(n=>n.kind==='index').config.registry=[];if(outcome==='ineligible')cfg.nodes.find(n=>n.kind==='period').config={start:'2022-01-01',end:'2022-12-31',dateRule:'published'};
 cfg.nodes=cfg.nodes.map(n=>['submit','ai'].includes(n.kind)?n:{...n,kind:'plugin',config:{plugin:'publication',tool:n.kind,settings:n.config}});
 const run=await runWorkflow(cfg);assert.equal(run.status,'awaiting-review');assert.equal(run.review.decision.status,outcome);assert.equal(run.review.score?.points??null,outcome==='clear'?24:null);
 }
});
